/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:e7ff31b3-3a70-4af6-a985-31d3c0165a03",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_69wgqY5aL",
    "aws_user_pools_web_client_id": "el4htmirfphofkl78vkdqnfdv",
    "oauth": {}
};


export default awsmobile;
