/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-3:304701460251",
    "aws_cognito_region": "eu-west-3",
    "aws_user_pools_id": "eu-west-3_I0hERRjHj",
    "aws_user_pools_web_client_id": "79ct68kfpulkt6cps7etbrll8e",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://xav72nlrsvebfozloirgxiimhi.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-j6wcyjkijbf3tfpdgfm2hx2wci"
};


export default awsmobile;
